<form id="reward-points-form" action="<?php echo $this->getUrl('rps/rp/post') ?>" method="post">
    <div class="discount">
        <h2><?php echo $this->__('Reward Points') ?></h2>
        <div class="discount-form">
            <label for="reward_points"><?php echo $this->__('Exchange your Reward Points!') ?></label>
            <p><?php $this->rewardPoints() ?></p>
            <input type="hidden" name="remove1" id="remove-points" value="0" />
            <div class="input-box">
                <input class="input-text" class="required-entry" id="reward_points" name="reward_points" value="" />
            </div>
            <div class="buttons-set">
                <button type="button" title="<?php echo $this->__('Exchange Reward Points') ?>" class="button" onclick="discountForm1.submit(false)" value="<?php echo $this->__('Exchange Reward Points') ?>"><span><span><?php echo $this->__('Exchange Reward Points') ?></span></span></button>
                <?php if(Mage::getSingleton('core/session')->getRewardPoints()): ?>
                    &nbsp; <button type="button" title="<?php echo $this->__('Cancel') ?>" class="button" onclick="discountForm1.submit(true)" value="<?php echo $this->__('Cancel') ?>"><span><span><?php echo $this->__('Cancel') ?></span></span></button>
                <?php endif;?>
            </div>
        </div>
    </div>
</form>
<form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
    <div class="discount">
        <h2><?php echo $this->__('Discount Codes') ?></h2>
        <div class="discount-form">
            <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.') ?></label>
            <input type="hidden" name="remove" id="remove-coupone" value="0" />
            <div class="input-box">
                <input class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>" />
            </div>
            <div class="buttons-set">
                <button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply Coupon') ?></span></span></button>
                <?php if(strlen($this->getCouponCode())): ?>
                    &nbsp; <button type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="button" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>"><span><span><?php echo $this->__('Cancel Coupon') ?></span></span></button>
                <?php endif;?>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
var discountForm1 = new VarienForm('reward-points-form');
discountForm1.submit = function (isRemove1) {
    if (isRemove1) {
        $('reward_points').removeClassName('required-entry validate-digits');
        $('remove-points').value = "1";
    } else {
        $('reward_points').addClassName('required-entry validate-digits');
        $('remove-points').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm1)();
}
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>
